#!/bin/sh

# swap mouse buttons
xmodmap -e "pointer = 3 2 1" &
# transparency program
xcompmgr &
# speed xrate up
xset r rate 300 50 &
# rat poison
unclutter &
dunst &

# tmux sessions
tmux new-session -t bg -d		# for usual programs that run on the background
